import pandas as pd

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('expand_frame_repr', False)
pd.set_option('display.width', None)
pd.set_option('display.max_colwidth', None)

# search_str1 | search_str2 |search_str3 | tactics | techniques | procedures | regex_value
data = [
    ["ntdll.dll", None, None, "Defense Evasion", "Indicator Removal from Tools", "Disable or modify system logs (ntdll.dll)", False],
    ["kernel32.dll", None, None, "Defense Evasion", "Obfuscated Files or Information", "Obfuscation of code or data (kernel32.dll)", False],
    ["amsi.dll", None, None, "Defense Evasion", "Exploitation for Privilege Escalation", "Abusing or bypassing security defenses like AMSI (amsi.dll)", False],
    ["wevtutil", None, None, "Defense Evasion", "Indicator Removal on Host: Clear Windows Event Logs", "Clear Security log using wevtutil cl Security silently (wevtutil)", False],
    ["EventLog", None, None, "Defense Evasion", "Indicator Removal from Tools", "Disable or modify system logs (EventLog)", False],
    ["winevt", None, None, "Defense Evasion", "Indicator Removal from Tools", "Delete or manipulate event logs (winevt)", False],
    ["auditpol", None, None, "Defense Evasion", "Indicator Removal from Tools", "Modify or disable auditing policy (auditpol)", False],
    ["clear", None, None, "Defense Evasion", "Indicator Removal from Tools", "Clear event logs (clear)", False],
    ["sysmon -c", None, None, "Defense Evasion", "Impair Defenses: Disable or Modify Tools", "Attackers attempt to stop, uninstall, corrupt, or disable Sysmon to blind defenders and hide malicious activity (sysmon -c)", False],
    ["sysmon", r"-accept", None, "Defense Evasion", "Impair Defenses: Disable or Modify Tools", "Attackers attempt to stop, uninstall, corrupt, or disable Sysmon to blind defenders and hide malicious activity (sysmon -accept)", False],
    ["curl.exe", None, None, "Command and Control / Exfiltration", "Ingress Tool Transfer", "curl.exe downloading or uploading payloads or data", False],
    ["certutil.exe", None, None, "Command and Control / Defense Evasion / Exfiltration", "Ingress Tool Transfer", "certutil.exe was used  to download payloads, encode, or decode files", False],
    ["cmd.exe", None, None, "Execution", "Command and Scripting Interpreter: Windows Command Shell", "cmd.exe was used  to execute commands or scripts", False],
    ["powershell", None, None, "Execution / Defense Evasion / Persistence", "Command and Scripting Interpreter: PowerShell", "PowerShell was used  for execution, obfuscation, or persistence", False],
    ["wscript.exe", None, None, "Execution / Defense Evasion", "Command and Scripting Interpreter: Visual Basic", "wscript.exe was used  to execute VBS or JS files", False],
    ["cscript.exe", None, None, "Execution", "Command and Scripting Interpreter: Visual Basic", "cscript.exe was used  to execute VBS or JS files", False],
    ["wscript.exe", r".js", None, "Execution", "Command and Scripting Interpreter: JavaScript", "wscript.exe executed JavaScript file", False],
    ["wscript.exe", r".vbs", None, "Execution", "Command and Scripting Interpreter: Visual Basic", "wscript.exe executed VBS file", False],
    ["wscript.exe", r".vb", None, "Execution", "Command and Scripting Interpreter: Visual Basic", "wscript.exe executed VB file", False],
    ["grantedAccess", "0x1010", "lsass.exe", "Credential Access", "OS Credential Dumping: LSASS Memory", "grantedAccess 0x1010 lsass.exe (handle access)", False],
    [r"eventID\":\"7045", None, None, "Persistence", "Create or Modify System Process: Windows Service", "Service Creation", False],
    ["sc create", None , None, "Persistence", "Create or Modify System Process: Windows Service", "Service Creation via sc.exe", False],
    ["schtasks", r"/create", None, "Persistence", "Scheduled Task/Job: Scheduled Task Creation", "Scheduled Task creation", False],
    [r"eventID\":\"4698", r"/create", None, "Persistence", "Scheduled Task/Job: Scheduled Task Creation", "Scheduled Task event and creation", False],
    [r"eventID\":\"7", None, None, "Execution and Defense Evasion", "Image Load", "Malicious or unauthorized images loaded into memory", False],
    [r"eventID\":\"12", None, None, "Defense Evasion", "Modify Registry", "Registry key creation detected", False],
    [r"eventID\":\"12", r"\run", None, "Persistence", "Boot or Logon Autostart Execution: Registry Run Keys/Startup Folder", "Persistence created in registry Run folder", False],
    [r"eventID\":\"13", None, None, "Defense Evasion", "Modify Registry", "Registry value set detected", False],
    ["Start Menu", r"Startup", None, "Persistence", "Boot or Logon Autostart Execution: Startup Folder", "File added to Startup location", False],
    [".zip", None, None, "Defense Evasion", "Archive Collected Data", "Zip archive file was used  for evasion or exfiltration", False],
    [".iso", None, None, "Defense Evasion", "Archive Collected Data", "ISO file was used  for evasion or staging", False],
    [".rar", None, None, "Defense Evasion", "Archive Collected Data", "RAR archive file was used  for evasion", False],
    [".lnk", None, None, "Execution", "User Execution: Malicious File", "Link file was used  to execute payloads", False],
    [".bat", None, None, "Execution", "Command and Scripting Interpreter: Windows Command Shell", "Batch file was used  for execution", False],
    ["net.exe", r"net user", None, "Persistence", "Account Manipulation: Create Account", "New user created via net.exe", False],
    ["net.exe", r"localgroup", r"admin", "Persistence", "Account Manipulation: Create Account", "Add user to administrators group", False],
    ["net.exe", r"domain admins", None, "Persistence", "Account Manipulation: Create Account", "Add user to domain admins", False],
    ["net.exe", None, None, "Discovery", "Account Discovery", "net.exe was used  for account or group enumeration", False],
    ["mshta.exe", r".hta", None, "Execution", "System Binary Proxy Execution: Mshta", "mshta.exe executed HTA payload", False],
    ["rundll32.exe", None, None, "Defense Evasion", "System Binary Proxy Execution: Rundll32", "rundll32.exe was used  to execute DLLs", False],
    ["rundll32.exe", r"http", None, "Defense Evasion", "System Binary Proxy Execution: Rundll32", "rundll32.exe loading external payload over HTTP", False],
    ["bitsadmin.exe", r"http", None, "Defense Evasion", "Ingress Tool Transfer", "bitsadmin.exe pulling payload from external server", False],
    ["bitsadmin.exe", None, None, "Defense Evasion", "Ingress Tool Transfer", "bitsadmin.exe was used  for file transfer", False],
    ["esentutl.exe", None, None, "Lateral Movement", "Transfer Data to Remote System", "esentutl.exe copying data across SMB share", False],
    ["msiexec.exe", r".msi", None, "Execution", "System Binary Proxy Execution: Msiexec", "msiexec.exe installing MSI payload", False],
    [r"Sysmon - Pipe Created", None, None, "Command and Control", "Non-Application Layer Protocol: Named Pipes", "Cobalt Strike uses named pipes", False],
    [r"Sysmon - Pipe Created", r"postex_", None, "Command and Control", "Non-Application Layer Protocol: Named Pipes", "Cobalt Strike post-exploitation pipe", False],
    [r"Sysmon - Pipe Created", r"msagent_", None, "Command and Control", "Non-Application Layer Protocol: Named Pipes", "Cobalt Strike msagent_ pipe", False],
    [r"Sysmon - Pipe Created", r"status_", None, "Command and Control", "Non-Application Layer Protocol: Named Pipes", "Cobalt Strike status_ pipe", False],
    [r"Sysmon - Pipe Created", r"MSSE", None, "Command and Control", "Non-Application Layer Protocol: Named Pipes", "Cobalt Strike MSSE pipe", False],
    [r"netscan.exe", None, None, "Discovery", "Network Service Discovery", "netscan.exe was used  to discover network services", False],
    [r"notepad.exe", None, None, "Defense Evasion", "Masquerading: Masquerade Task or Service", "notepad.exe was used  for process injection", False],
    [r"netsh.exe", None, None, "Defense Evasion / Command and Control", "Modify System Firewall", "netsh.exe modifying firewall rules", False],
    [r"netsh.exe", r"3389", None, "Command and Control", "Remote Services: RDP", "Firewall port 3389 opened", False],
    [r"netsh.exe", r"firewall", r"enable", "Command and Control", "Modify System Firewall", "Firewall rule enabled", False],
    [r"Invoke-SessionGopher", None, None, "Credential Access", "Unsecured Credentials: Private Keys", "Invoke-SessionGopher PowerShell credential tool", False],
    [r"smbexec", None, None, "Lateral Movement", "Remote Services: SMB/Windows Admin Shares", "smbexec lateral tool was used ", False],
    [r"psexec", None, None, "Lateral Movement", "Remote Services: SMB/Windows Admin Shares", "psexec tool usage", False],
    [r"cmd.exe", r"/Q", r"/c", "Lateral Movement", "Remote Services: SMB/Windows Admin Shares", "Impacket or psexec-like tool usage", False],
    [r"cmd.exe", r"wmic", None, "Lateral Movement", "Remote Services: Windows Management Instrumentation", "WMIC was used  via cmd", False],
    [r"cmd.exe", r"--username", None, "Credential Access", "Use Alternate Authentication Material: Pass the Hash", "Pass-the-Hash attack via cmd.exe", False],
    [r"whoami", None, None, "Discovery", "System Owner/User Discovery", "whoami command was used ", False],
    [r"explorer.exe", r".dll", None, "Defense Evasion", "Process Injection", "explorer.exe injecting DLL", False],
    [r"msDS-AllowedToDelegateTo", None, None, "Credential Access", "Abuse Elevation Control Mechanism: Kerberos Delegation", "Check msDS-AllowedToDelegateTo attribute", False],
    [r"rundll32.exe", r",a /p:", None, "Command and Control", "System Binary Proxy Execution: Rundll32", "Cobalt Strike encoded command using rundll32", False],
    [r"wmic.exe", None, None, "Execution", "Windows Management Instrumentation", "wmic.exe execution", False],
    [r"systeminfo", None, None, "Discovery", "System Information Discovery", "systeminfo command was used ", False],
    [r"ping.exe", None, None, "Discovery", "Network Service Discovery", "ping.exe network check", False],
    [r"excel.exe", r"powershell", None, "Execution", "Command and Scripting Interpreter: PowerShell", "Suspicious Excel child process to PowerShell", False],
    [r"excel.exe", r"cmd.exe", None, "Execution", "Command and Scripting Interpreter: Windows Command Shell", "Suspicious Excel child process to cmd.exe", False],
    [r"word.exe", r"powershell", None, "Execution", "Command and Scripting Interpreter: PowerShell", "Suspicious Word child process to PowerShell", False],
    [r"word.exe", r"cmd.exe", None, "Execution", "Command and Scripting Interpreter: Windows Command Shell", "Suspicious Word child process to cmd.exe", False],
    [r".one", None, None, "Execution", "User Execution: Malicious File", ".one file was potentially used  for payloads", False],
    [r"Download", None, None, "Collection", "Data from Local System", "Check Downloads directory for suspicious files", False],
    [r"url=http", None, None, "Command and Control", "Ingress Tool Transfer", "url=http in command or script", False],
    [r"vssadmin", None, None, "Impact", "Inhibit System Recovery", "vssadmin was used  to delete or manipulate shadow copies", False],
    [r"Process Access", None, None, "Defense Evasion", "Process Injection", "Process Access flag may indicate injection attempt", False],
    [r"pastebin", None, None, "Command and Control", "Web Service: Upload Tool", "pastebin was used to host payloads or C2 data", False],
]


mitre_attck_df = pd.DataFrame(data, columns=["search_str1","search_str2","search_str3","tactics", "techniques", "procedures", "regex_value"])
